CREATE TABLE CATEGORIES
(
    CATEGORY VARCHAR(30) primary key
);

INSERT INTO CATEGORIES(CATEGORY) VALUES ('global');
INSERT INTO CATEGORIES(CATEGORY) VALUES ('facet');
INSERT INTO CATEGORIES(CATEGORY) VALUES ('content');